In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
import torch

### Declare tensors

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[9.1837e-39, 8.4490e-39, 1.0102e-38],
        [8.4490e-39, 9.2755e-39, 1.0837e-38],
        [6.9796e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8267, 0.2978, 0.4275],
        [0.3966, 0.5480, 0.7172],
        [0.2154, 0.0800, 0.8614],
        [0.0572, 0.8954, 0.3276],
        [0.8796, 0.3591, 0.7429]])


Construct a matrix filled zeros and of dtype long:



In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
torch.ones(5, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


### Create a tensor based on an existing tensor. 
These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9140,  0.1494,  0.2544],
        [ 1.3320,  0.2616,  0.2104],
        [-1.1701,  0.9277, -0.0525],
        [-0.9727,  0.0562, -0.5014],
        [-0.6115,  1.7091, -0.3916]])


Get its size:



In [10]:
print(x.size())

torch.Size([5, 3])


#### Note: ``torch.Size`` is in fact a tuple, so it supports all tuple operations

### Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1564,  0.5043, -0.7660],
        [ 0.5105,  1.2330,  0.8707],
        [ 0.9446, -1.4255, -0.1323],
        [ 1.2130,  0.3619,  0.2404],
        [ 0.8061, -1.5928,  0.2853]])


Addition: syntax 2



In [12]:
print(torch.add(x, y))

tensor([[ 1.1564,  0.5043, -0.7660],
        [ 0.5105,  1.2330,  0.8707],
        [ 0.9446, -1.4255, -0.1323],
        [ 1.2130,  0.3619,  0.2404],
        [ 0.8061, -1.5928,  0.2853]])


Addition: providing an output tensor as argument



In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1564,  0.5043, -0.7660],
        [ 0.5105,  1.2330,  0.8707],
        [ 0.9446, -1.4255, -0.1323],
        [ 1.2130,  0.3619,  0.2404],
        [ 0.8061, -1.5928,  0.2853]])


Addition: in-place



In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1564,  0.5043, -0.7660],
        [ 0.5105,  1.2330,  0.8707],
        [ 0.9446, -1.4255, -0.1323],
        [ 1.2130,  0.3619,  0.2404],
        [ 0.8061, -1.5928,  0.2853]])


#### Note: Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``

### Indexing, resizing
You can use standard NumPy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([ 0.3699,  0.6245, -1.4826, -0.5761, -1.7392])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
print(x)
print(y)
print(z)

tensor([[-0.8299, -0.1009,  0.3219,  0.6279],
        [ 0.2237,  1.0795,  0.7293, -0.2002],
        [-2.0755, -0.9067, -0.2183, -0.4025],
        [ 1.1528, -0.7979, -0.4726,  0.9141]])
tensor([-0.8299, -0.1009,  0.3219,  0.6279,  0.2237,  1.0795,  0.7293, -0.2002,
        -2.0755, -0.9067, -0.2183, -0.4025,  1.1528, -0.7979, -0.4726,  0.9141])
tensor([[-0.8299, -0.1009,  0.3219,  0.6279,  0.2237,  1.0795,  0.7293, -0.2002],
        [-2.0755, -0.9067, -0.2183, -0.4025,  1.1528, -0.7979, -0.4726,  0.9141]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [13]:
x = torch.randn(1)
print(x)
print(x.item(), type(x.item()))

tensor([0.8863])
0.8863378167152405 <class 'float'>


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [15]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.8863], device='cuda:0')
tensor([1.8863], dtype=torch.float64)
